const data = [
  {
    title: "TYPING",
    url: "https://daihachi10.github.io/program/01/index.html",
    description: "１文字づつの入力するスピードがどんどん早くなるタイピングです。入力した数によってランクが付きます。ESCキーで一時停止、ENTERキーで再開します。キー音&copy;otologic",
    img: "../images/program-img/img-item01.webp",
    searchText: "TYPING TYPING １文字づつの入力するスピードがどんどん早くなるタイピングです。入力した数によってランクが付きます。ESCキーで一時停止、ENTERキーで再開します。キー音&copy;otologic TYPING タイピング TYPING １文字づつの入力するスピードがどんどん早くなるタイピングです。入力した数によってランクが付きます。 ESCキーで一時停止、ENTERキーで再開します。 キー音&copy;otologic STARTボタンを押すと開始します。 START/RESET VIEW CODE ADVERTISEMENT",
  },
  {
    title: "PASSWORD GENERATOR",
    url: "https://daihachi10.github.io/program/02/index.html",
    description: "大文字、小文字、数字を含む強力なパスワードをランダムで生成します。よいパスワードが思いつかないときに。生成開始ボタンをクリックして生成を開始します。",
    img: "../images/program-img/img-item02.webp",
    searchText: "PASSWORD GENERATOR PASSWORD GENERATOR 大文字、小文字、数字を含む強力なパスワードをランダムで生成します。よいパスワードが思いつかないときに。生成開始ボタンをクリックして生成を開始します。 PASSWORD GENERATOR パスワード生成機 PASSWORD GENERATOR 大文字、小文字、数字を含む強力なパスワードをランダムで生成します。よいパスワードが思いつかないときに。 生成開始ボタンをクリックして生成を開始します。 STARTボタンを押すと開始します。 START/RESET VIEW CODE ADVERTISEMENT",
  },
  {
    title: "BALL PICKING GAME",
    url: "https://daihachi10.github.io/program/03/index.html",
    description: "ボール拾いゲーム。スコアが増えるごとにボールのスピードが早くなる。ラッキーボールやアンラッキーボールも。 操作方法を変更ボタンでキーボード/マウス・タップ操作を切り替えます。",
    img: "../images/program-img/img-item03.webp",
    searchText: "BALL PICKING GAME BALL PICKING GAME ボール拾いゲーム。スコアが増えるごとにボールのスピードが早くなる。ラッキーボールやアンラッキーボールも。 操作方法を変更ボタンでキーボード/マウス・タップ操作を切り替えます。 BALL PICKING GAME ボール拾いゲーム BALL PICKING GAME ボール拾いゲーム。スコアが増えるごとにボールのスピードが早くなる。ラッキーボールやアンラッキーボールも。 操作方法を変更ボタンでキーボード/マウス・タップ操作を切り替えます。 STARTボタンを押すと開始します。 操作方法を変更 START/RESET VIEW CODE ADVERTISEMENT",
  },
  {
    title: "EMOJI GENERATOR",
    url: "https://daihachi10.github.io/program/04/index.html",
    description: "絵文字生成機です。ランダムで100行絵文字を生成します。友達にLINE®を送信するときに使えるかもしれませんね。",
    img: "../images/program-img/img-item04.webp",
    searchText: "EMOJI GENERATOR EMOJI GENERATOR 絵文字生成機です。ランダムで100行絵文字を生成します。友達にLINE®を送信するときに使えるかもしれませんね。 EMOJI GENERATOR 絵文字生成機 EMOJI GENERATOR 絵文字生成機です。ランダムで100行絵文字を生成します。友達にLINE®を送信するときに使えるかもしれませんね。 START/RESETボタンを押すと開始します。 START/RESET VIEW CODE ADVERTISEMENT PROGRAM LIST SUSHITYPING HOT BuildpcPartsIntroduction HOT NOTEPAD HOT TETR HOT SCROLLING PLATFORMER MAKER GAME Geometry Dash Minecraft version GAME Geometry Dash Minecraft version2 GAME LASERS || a mobile platformer GAME BATTLE ROYAL GAME BALL PICKING GA",
  },
  {
    title: "QR CODE GENERATOR",
    url: "https://daihachi10.github.io/program/05/index.html",
    description: "QRコード®を生成します。このサイトのURLが指定されています。サイトを共有するときに使えるかもしれません。",
    img: "../images/program-img/img-item05.webp",
    searchText: "QR CODE GENERATOR QR CODE GENERATOR QRコード®を生成します。このサイトのURLが指定されています。サイトを共有するときに使えるかもしれません。 QR CODE GENERATOR QRコード生成機 QR CODE GENERATOR QRコード®を生成します。このサイトのURLが指定されています。サイトを共有するときに使えるかもしれません。 START/RESETボタンを押すと開始します。 START/RESET VIEW CODE ADVERTISEMENT",
  },
  {
    title: "SCROLLING PLATFORMER MAKER",
    url: "https://daihachi10.github.io/program/06/index.html",
    description: "スクロールプラットフォーマーを作ってみよう！",
    img: "../images/program-img/img-item06.webp",
    searchText: "SCROLLING PLATFORMER MAKER SCROLLING PLATFORMER MAKER スクロールプラットフォーマーを作ってみよう！ SCROLLING PLATFORMER MAKER スクロールプラットフォーマーメーカー【モバイル対応】 SCROLLING PLATFORMER MAKER --> スクロールプラットフォーマーを作ってみよう！ キー(0-9)でブロック選択 モバイルの設定をクリック(左上) エクスポートボタンを使ってレベルのコードを取得する \"e \"で記号の名前を変更する VIEW CODE ADVERTISEMENT",
  },
  {
    title: "Geometry Dash Minecraft version",
    url: "https://daihachi10.github.io/program/07/index.html",
    description: "ジオメトリーダッシュのマイクラ版！ 矢印上・スペースキー・タップで操作できます（ジャンプ）",
    img: "../images/program-img/img-item07.webp",
    searchText: "Geometry Dash Minecraft version Geometry Dash Minecraft version ジオメトリーダッシュのマイクラ版！ 矢印上・スペースキー・タップで操作できます（ジャンプ） Geometry Dash Minecraft version ジオメトリーダッシュ Minecraft版 Geometry Dash Minecraft version --> ジオメトリーダッシュのマイクラ版！ 矢印上・スペースキー・タップで操作できます（ジャンプ） VIEW CODE ADVERTISEMENT",
  },
  {
    title: "Geometry Dash Minecraft version2",
    url: "https://daihachi10.github.io/program/08/index.html",
    description: "ジオメトリーダッシュのマイクラ版2！ 矢印上・スペースキー・タップで操作できます（ジャンプ）",
    img: "../images/program-img/img-item08.webp",
    searchText: "Geometry Dash Minecraft version2 Geometry Dash Minecraft version2 ジオメトリーダッシュのマイクラ版2！ 矢印上・スペースキー・タップで操作できます（ジャンプ） Geometry Dash Minecraft version2 ジオメトリーダッシュ Minecraft版2 Geometry Dash Minecraft version ジオメトリーダッシュのマイクラ版2！ 矢印上・スペースキー・タップで操作できます（ジャンプ） VIEW CODE ADVERTISEMENT INSTALL APP MY PROGRAM ENGLISH HIRAGANA daihachi &copy;daihachi",
  },
  {
    title: "LASERS || a mobile platformer",
    url: "https://daihachi10.github.io/program/09/index.html",
    description: "WASD、矢印キー、タップで移動 レーザーに当たらないようにクリアしよう Rキー、RESETボタンを押すとステージがリセットされます",
    img: "../images/program-img/img-item09.webp",
    searchText: "LASERS || a mobile platformer LASERS || a mobile platformer WASD、矢印キー、タップで移動 レーザーに当たらないようにクリアしよう Rキー、RESETボタンを押すとステージがリセットされます LASERS || a mobile platformer レーザーをよけろ Geometry Dash Minecraft version WASD、矢印キー、タップで移動 レーザーに当たらないようにクリアしよう Rキー、RESETボタンを押すとステージがリセットされます VIEW CODE ADVERTISEMENT",
  },
  {
    title: "P5 ANIMATION 02",
    url: "https://daihachi10.github.io/program/10/index.html",
    description: "P5 ANIMATION 02",
    img: "../images/program-img/img-item10.webp",
    searchText: "P5 ANIMATION 02 P5 ANIMATION 02 P5 ANIMATION 02 P5 ANIMATION 02 P5 アニメーション 02 P5 ANIMATION 02 P5 ANIMATION 02 緑色の小さな正方形が斜めに一直線に並んでいるデザインです。シンプルでミニマルな構図で、各正方形が均等な間隔で配置されているのが特徴です。 STARTボタンを押すと開始します。 START/RESET VIEW CODE ADVERTISEMENT",
  },
  {
    title: "P5 ANIMATION 01",
    url: "https://daihachi10.github.io/program/11/index.html",
    description: "P5 ANIMATION 01",
    img: "../images/program-img/img-item11.webp",
    searchText: "P5 ANIMATION 01 P5 ANIMATION 01 P5 ANIMATION 01 読み込み中... --> P5 ANIMATION 01 P5 アニメーション 01 P5 ANIMATION 01 P5 ANIMATION 01 鮮やかな色の四方に広がる星形模様が円形の点線で囲まれた、幾何学的で対称的なデザインです。 設定は自動保存されます。 STARTボタンを押すと開始します。 START/RESET SPEEDUP --> BACK PATTERN --> NEXT PATTERN --> BACKGROUND --> ▼ SETTINGS SETTINGS RESET SPEEDUP BACK PATTERN NEXT PATTERN BACKGROUND VIEW CODE ADVERTISEMENT",
  },
  {
    title: "P5 ANIMATION 03",
    url: "https://daihachi10.github.io/program/12/index.html",
    description: "P5 ANIMATION 03",
    img: "../images/program-img/img-item12.webp",
    searchText: "P5 ANIMATION 03 P5 ANIMATION 03 P5 ANIMATION 03 P5 ANIMATION 03 P5 アニメーション 03 P5 ANIMATION 03 P5 ANIMATION 03 赤、青、緑の円が重なり合ってランダムに配置されたデザインです。円の大きさや位置に変化があり、白い背景とのコントラストが目立ちます。全体的にポップでカラフルな印象を与えるアブストラクトな模様です。 STARTボタンを押すと開始します。 START/RESET VIEW CODE ADVERTISEMENT",
  },
  {
    title: "BATTLE ROYAL",
    url: "https://daihachi10.github.io/program/13/index.html",
    description: "大乱闘のプログラムがプレイができるサイトです。",
    img: "../images/program-img/img-item13.webp",
    searchText: "BATTLE ROYAL BATTLE ROYAL 大乱闘のプログラムがプレイができるサイトです。 BATTLE ROYAL 大乱闘 BATTLE ROYAL --> 大乱闘! スペースキーを押しながらジョンの冒険を押すと… VIEW CODE ADVERTISEMENT",
  },
  {
    title: "NOTEPAD | daihachi offical website",
    url: "https://daihachi10.github.io/program/14/index.html",
    description: "daihachi",
    img: "../images/program-img/img-item14.webp",
    searchText: "NOTEPAD | daihachi offical website タイトル daihachi daihachi INSTALL APP MY PROGRAM ENGLISH HIRAGANA YOUTUBE --> タイトル 本文 .txtとして保存 一時的に保存 コピー --> 画像をアップロード リセット INSTALL APP MY PROGRAM ENGLISH HIRAGANA daihachi &copy;daihachi",
  },
  {
    title: "SUSHITYPING",
    url: "https://daihachi10.github.io/program/15/index.html",
    description: "『寿司タイピング』はローマ字入力用のタイピング練習ゲームです。 回転寿司のお皿が流れてしまう前に画面の文字をタイプして、どれだけ寿司を取れるか（= たくさん食べられるか）を競います。(寿司打) 効果音...",
    img: "../images/program-img/img-item15.webp",
    searchText: "SUSHITYPING SUSHITYPING 『寿司タイピング』はローマ字入力用のタイピング練習ゲームです。 回転寿司のお皿が流れてしまう前に画面の文字をタイプして、どれだけ寿司を取れるか（= たくさん食べられるか）を競います。(寿司打) 効果音... SUSHITYPING 寿司タイピング TYPING 『寿司タイピング』はローマ字入力用のタイピング練習ゲームです。 回転寿司のお皿が流れてしまう前に画面の文字をタイプして、どれだけ寿司を取れるか（= たくさん食べられるか）を競います。(寿司打) 効果音&copy;otologic 本家様 : sushida.net VIEW CODE ADVERTISEMENT",
  },
  {
    title: "読み込み中",
    url: "https://daihachi10.github.io/program/16/index.html",
    description: "自作パソコンのパーツ・メリットデメリット・などを詳しく紹介しているサイトです",
    img: "../images/program-img/img-item16.webp",
    searchText: "読み込み中 Build             PC             Parts             Introduction 自作パソコンのパーツ・メリットデメリット・などを詳しく紹介しているサイトです BuildPC ABOUT PARTS LIST MOVIE HOW TO BUILD --> --> --> DARK --> LIGHT --> JP / EN --> BuildPC ABOUT PARTS LIST MOVIE HOW TO BUILD --> --> --> DARK --> LIGHT --> JP / EN --> PICTURE RECOMMENDED STORES DARK LIGHT SOUND JA / EN --> Build PC Parts Introduction 10 自作パソコンパーツ紹介 2 そもそも自作パソコンとは？ 2 自作パソコンの動画 2 自作パソコンの組み立て方 2 自作パソコンの写真 2 自作パソコンパーツ紹介 2 そもそも自作パソコンとは？ 2 自作パソコンの動画 2 自作パソコンの組み立て方 2 自",
  },
  {
    title: "YouTube Video Player",
    url: "https://daihachi10.github.io/program/17/index.html",
    description: "Enter a YouTube URL to display the video:",
    img: "../images/program-img/img-item.webp",
    searchText: "YouTube Video Player YouTube Video Player Enter a YouTube URL to display the video: YouTube Video Player Enter a YouTube URL to display the video: Load Video",
  },
  {
    title: "Program 19",
    url: "https://daihachi10.github.io/program/19/index.html",
    description: "Program 19のページです。",
    img: "../images/program-img/img-item.webp",
    searchText: "Program 19 Program 19のページです。",
  },
  {
    title: "TETR",
    url: "https://daihachi10.github.io/program/20/index.html",
    description: "シンプルなテト風のゲームです。ENTERキーまたはスタートボタンでスタート 更新されない場合はCtrl + Shift + Rを押してください",
    img: "../images/program-img/img-item20.webp",
    tags: ["テトリス", "テト", "落ち物パズル", "tetris", "パズルゲーム", "ブロック", "TETR"],
    searchText: "TETR TETR シンプルなテト風のゲームです。ENTERキーまたはスタートボタンでスタート 更新されない場合はCtrl + Shift + Rを押してください テトリス テト 落ち物パズル tetris パズルゲーム ブロック TETR daihachi INSTALL APP MY PROGRAM ENGLISH LOGIN / SIGNUP --> TETR テト TETR シンプルなテト風のゲームです。 ENTERキーまたはスタートボタンでスタート 更新されない場合は Ctrl + Shift + R を押してください VIEW CODE --> ゲームがスタートできなくなった場合 ADVERTISEMENT &times; New Release! スコア機能 追加 1ライン 消すとスコアが1増えます。 -->",
  },
  {
    title: "REPRODUCED IN PACMAN",
    url: "https://daihachi10.github.io/program/21/index.html",
    description: "figma",
    img: "../images/program-img/img-item.webp",
    searchText: "REPRODUCED IN PACMAN REPRODUCED IN PACMAN figma REPRODUCED IN PACMAN パックマンを再現 パックマンを再現 パックマンを再現しました。 全画面表示モード ADVERTISEMENT",
  },
  {
    title: "Hub",
    url: "https://daihachi10.github.io/program/22/index.html",
    description: "Hubのページです。",
    img: "../images/program-img/img-item.webp",
    searchText: "Hub Hubのページです。 --> More forecasts: 天気 10日間 東京 --> --> 10日間天気--> --> Google Youtube X Gmail DeepL",
  },
  {
    title: "website",
    url: "https://daihachi10.github.io/program/24/index.html",
    description: "description",
    img: "../images/program-img/img-item.webp",
    searchText: "website TITLE description 読み込み中... --> nvidia H1 H2 H3 H4 nvidia H1 H2 H3 H4 TITLE SUBTITLE headline この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。この文章はダミーです。文字の大きさ、量、字間、行間等を確認するために入れています。 BUTTON headline title1 Description title2 Description title3 Description title4 Description BUTTON SUPPORT MOVIE headline >>>>>> 95eeb45c6041ac16e7982812e1bfee0617630ad9 allow=\"accelerometer; a",
  },
  {
    title: "2DShootingGame",
    url: "https://daihachi10.github.io/program/25/index.html",
    description: "大乱闘のプログラムがプレイができるサイトです。",
    img: "../images/program-img/img-item25.webp",
    searchText: "2DShootingGame 2DShootingGame 大乱闘のプログラムがプレイができるサイトです。 2DShootingGame 2Dシューティングゲーム 2DShootingGame --> 2Dのシューティングゲームです。 コインをためて銃を強化していくゲームです。 全画面表示モード ADVERTISEMENT",
  },
  {
    title: "Program 26",
    url: "https://daihachi10.github.io/program/26/index.html",
    description: "変換を含むタイピングができます。",
    img: "../images/program-img/img-item.webp",
    searchText: "Program 26 変換を含むタイピングができます。 制限時間: 60 秒 再挑戦",
  },
  {
    title: "REPRODUCED IN FIGMA",
    url: "https://daihachi10.github.io/program/30/index.html",
    description: "figma",
    img: "../images/program-img/img-item30.webp",
    searchText: "REPRODUCED IN FIGMA REPRODUCED IN FIGMA figma REPRODUCED IN FIGMA Figmaで再現 REPRODUCED IN FIGMA --> ホームページをfigmaで再現してみましたアニメーションこだわった！ アニメーションを再生 全画面表示モード ADVERTISEMENT",
  },
  {
    title: "reCAPTCHA",
    url: "https://daihachi10.github.io/program/31/index.html",
    description: "figma",
    img: "../images/program-img/img-item31.webp",
    searchText: "reCAPTCHA reCAPTCHA figma reCAPTCHA reCAPTCHA reCAPTCHA --> たくさんreCAPTCHA アニメーションを再生 --> 全画面表示モード --> ADVERTISEMENT",
  },
  {
    title: "Grid Layout",
    url: "https://daihachi10.github.io/program/32/index.html",
    description: "figma",
    img: "../images/program-img/img-item.webp",
    searchText: "Grid Layout Grid Layout figma Grid Layout Grid Layout Grid Layout --> 1 2 3 4 5 7 Grid Layout アニメーションを再生 --> 全画面表示モード --> ADVERTISEMENT",
  },
  {
    title: "SnakeGame",
    url: "https://daihachi10.github.io/program/33/index.html",
    description: "ヘビゲームの再現をしました。りんごを食べると体が伸び、自分の身体に触れるとゲームオーバーです。",
    img: "../images/program-img/img-item33.webp",
    tags: ["ヘビゲーム", "スネーク", "snake", "スネークゲーム", "ヘビ"],
    searchText: "SnakeGame SnakeGame ヘビゲームの再現をしました。りんごを食べると体が伸び、自分の身体に触れるとゲームオーバーです。 ヘビゲーム スネーク snake スネークゲーム ヘビ --> SnakeGame ヘビゲーム SnakeGame 非公開に設定されています。 プログラム一覧に戻る --> ↑ --> ← --> ↓ --> → --> ヘビゲームの再現をしました。りんごを食べると体が伸び、自分の身体に触れるとゲームオーバーです。 残り時間 1Playerスタート 2Playersスタート リスタート すり抜けを有効にする --> 時間を変更する Googleヘビゲーム VIEW CODE ADVERTISEMENT -->",
  },
  {
    title: "AI自動運転＆学習（AI）",
    url: "https://daihachi10.github.io/program/34/index.html",
    description: "figma",
    img: "../images/program-img/img-item34.webp",
    searchText: "AI自動運転＆学習（AI） AI自動運転＆学習（AI） figma AI自動運転＆学習（AI） AI Automated Driving & Learning (AI) REPRODUCED IN FIGMA --> 全画面表示モードで実行することをおすすめします クリックで道路を描く。 うまくいかないときはスタートやロードを数回クリックしてください。 学習済みデータ(3回クリックで全選択) {\"bestBrain\":{\"inputNodes\":5,\"hiddenNodes\":6,\"outputNodes\":2,\"weights_ih\":[[-0.2459955336201296,0.7547445091830407,0.34792212822035173,-0.6451996849136861,0.21766617358142515],[0.18489218699581544,0.8222251402376606,-0.19157438216104827,-1.1503322500517783,-0.9853469267283907],[0.05261673065742656,0.1",
  },
  {
    title: "game",
    url: "https://daihachi10.github.io/program/35/index.html",
    description: "gameのページです。",
    img: "../images/program-img/img-item35.webp",
    searchText: "game gameのページです。 答え 7 8 9 4 5 6 1 2 3 - 0 ← スタート 足し算 引き算 掛け算 出てくる数字の最大値を変更 モードをランダムにするか",
  },
  {
    title: "DOM操作",
    url: "https://daihachi10.github.io/program/36/index.html",
    description: "DOM操作のページです。",
    img: "../images/program-img/img-item.webp",
    searchText: "DOM操作 こんにちは。世界 DOM操作のページです。 こんにちは。世界 押せ",
  },
  {
    title: "3:1",
    url: "https://daihachi10.github.io/program/37/index.html",
    description: "3:1",
    img: "../images/program-img/img-item.webp",
    searchText: "3:1 3:1 3:1 3:1 3:1 3:1 3:1 STARTボタンを押すと開始します。 START/RESET VIEW CODE ADVERTISEMENT",
  },
  {
    title: "Program 38",
    url: "https://daihachi10.github.io/program/38/index.html",
    description: "Program 38のページです。",
    img: "../images/program-img/img-item.webp",
    searchText: "Program 38 Program 38のページです。 -->",
  },
  {
    title: "Monkeytype Clone",
    url: "https://daihachi10.github.io/program/39/index.html",
    description: "Monkeytype Cloneのページです。",
    img: "../images/program-img/img-item.webp",
    searchText: "Monkeytype Clone Monkeytype Cloneのページです。 結果 wpm 0 acc 0% zen Olivia Monkeytype Dracula Aurora Serika Sakura esc - restart",
  },
  {
    title: "Gemini CLI - Your AI Coding Partner",
    url: "https://daihachi10.github.io/program/40/index.html",
    description: "コードの文脈を深く理解し、的確なリファクタリングやバグ修正を提案します。",
    img: "../images/program-img/img-item.webp",
    searchText: "Gemini CLI - Your AI Coding Partner コードの文脈を深く理解し、的確なリファクタリングやバグ修正を提案します。 JP / EN ターミナルから、AIの力を最大限に引き出す。 主な特徴 🧠 インテリジェントなコード理解 + コードの文脈を深く理解し、的確なリファクタリングやバグ修正を提案します。 高度なAIモデルを活用し、コード構造を分析し、パターンを特定し、文脈に応じた改善を提案します。複雑なリファクタリング作業、バグ検出、さらには意図に基づいた新しいコードスニペットの生成にも役立ちます。 🛠️ シームレスなツール連携 + Gitやファイルシステムなど、既存のツールとスムーズに連携し、開発フローを妨げません。 ターミナル内で直接動作し、ローカルファイルシステム、Gitリポジトリ、その他のコマンドラインツールと連携します。これにより、コンテキストを切り替えることなく、自然で効率的な開発体験を保証します。 🛡️ 安全なコマンド実行 + 実行前にコマンドの目的と影響を説明し、ユーザーの承認を得ることで安全性を確保します。 コマンドを実行する前に、Gem",
  },
  {
    title: "Program 41",
    url: "https://daihachi10.github.io/program/41/index.html",
    description: "Cloudflareに接続しています...",
    img: "../images/program-img/img-item.webp",
    searchText: "Program 41 Cloudflareに接続しています...",
  },
  {
    title: "AI Chat",
    url: "https://daihachi10.github.io/program/42/index.html",
    description: "AI Chatのページです。",
    img: "../images/program-img/img-item.webp",
    searchText: "AI Chat AI Chat AI Chatのページです。 チャット履歴 add_comment settings AI Chat APIキーを設定して、メッセージを送信してください。 send 設定 &times; Google AI Studio APIキー テーマ dark_mode 保存",
  },
  {
    title: "Gemini & マルコフ連鎖 AI",
    url: "https://daihachi10.github.io/program/43/index.html",
    description: "お持ちのGoogle AI APIキーと、生成したい文章の指示（プロンプト）を入力してください。",
    img: "../images/program-img/img-item.webp",
    searchText: "Gemini & マルコフ連鎖 AI Gemini & マルコフ連鎖 AI お持ちのGoogle AI APIキーと、生成したい文章の指示（プロンプト）を入力してください。 Gemini & マルコフ連鎖 AI Step 1: Gemini APIで文章を生成 お持ちのGoogle AI APIキーと、生成したい文章の指示（プロンプト）を入力してください。 Geminiから文章を取得 Step 2: マルコフ連鎖で新しい文章を生成 Geminiが生成した文章（または手動で入力した文章）を使って、マルコフ連鎖による新しい文章を生成します。 マルコフ連鎖で生成 生成された文章 単語の遷移確率",
  },
  {
    title: "ホーム",
    url: "https://daihachi10.github.io/index.html",
    description: "daihachiの公式サイト",
    img: "../images/program-img/img-item.webp",
    searchText: "ホーム ホーム daihachiの公式サイト",
  },
  {
    title: "プログラム一覧",
    url: "https://daihachi10.github.io/program.html",
    description: "daihachiが制作したプログラム一覧です。",
    img: "../images/program-img/img-item.webp",
    searchText: "プログラム一覧 プログラム一覧 daihachiが制作したプログラム一覧です。",
  },
  {
    title: "INSTALL",
    url: "https://daihachi10.github.io/install.html",
    description: "daihachiアプリをインストール",
    img: "../images/program-img/img-item.webp",
    searchText: "INSTALL インストール daihachiアプリをインストール",
  },
  {
    title: "お問い合わせフォーム",
    url: "https://daihachi10.github.io/contact.html",
    description: "お問い合わせのページです。",
    img: "../images/program-img/img-item.webp",
    searchText: "お問い合わせフォーム お問い合わせ お問い合わせのページです。",
  },
  {
    title: "English",
    url: "https://daihachi10.github.io/en.html",
    description: "daihachiの公式サイト",
    img: "../images/program-img/img-item.webp",
    searchText: "English English daihachiの公式サイト",
  },
  {
    title: "ルーレット",
    url: "https://daihachi10.github.io/roulette/index.html",
    description: "シンプルで使いやすいオンラインルーレット。人数や数値範囲、名前リスト対応、履歴保存やプロファイル管理、カード機能まで備えた多機能ツールです。",
    img: "../images/program-img/img-item.webp",
    searchText: "ルーレット ルーレット シンプルで使いやすいオンラインルーレット。人数や数値範囲、名前リスト対応、履歴保存やプロファイル管理、カード機能まで備えた多機能ツールです。",
  },
  {
    title: "あきリスト",
    url: "https://daihachi10.github.io/calendar/index.html",
    description: "あきリストは、空いている日をカレンダーで選んで画像として共有できるシンプルなスケジュール共有アプリです。終日・午前・午後をタップで簡単に設定できます。",
    img: "../images/program-img/img-item.webp",
    searchText: "あきリスト カレンダー あきリストは、空いている日をカレンダーで選んで画像として共有できるシンプルなスケジュール共有アプリです。終日・午前・午後をタップで簡単に設定できます。",
  },
];

const imagelist = [
  "../images/usericons/01.webp",
  "../images/usericons/02.webp",
  "../images/usericons/03.webp",
  "../images/usericons/04.webp",
  "../images/usericons/05.webp",
  "../images/usericons/06.webp",
  "../images/usericons/07.webp",
  "../images/usericons/08.webp",
  "../images/usericons/09.webp",
  "../images/usericons/10.webp",
  "../images/usericons/11.webp",
];
